name: binaries

on: push

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
    - run: brew install octave
    - run: octave

  osx:
    runs-on: macos-12
    steps:
    - run: brew install octave
    - run: octave
    
  osx-m1:
    runs-on: self-hosted
    steps:
    - run: brew install octave
    - run: octave
    
  windows:
    runs-on: windows-latest
    steps:
    - run: C:\msys64\usr\bin\wget.exe wget https://ftpmirror.gnu.org/octave/windows/octave-7.3.0-w64.zip
    - run: unzip octave-7.3.0-w64.zip -d octave
    - run: octave/mingw64/bin/octave.exe
    
