name: binaries

on: push

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - run: homebrew install octave
    - run: octave

  osx:
    runs-on: macos-11
    steps:
    - run: brew install octave
    - run: octave
    
  osx-m1:
    runs-on: self-hosted
    steps:
    - run: brew install octave
    - run: octave
    
  windows:
    runs-on: windows-latest
    steps:
    - run: wget https://ftpmirror.gnu.org/octave/windows/octave-7.3.0-w64.zip
    - run: unzip octave-7.3.0-w64.zip -d octave
    - run: octave/mingw64/bin/octave.exe
    
