name: dev-release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
    
jobs:
  dev-release:
    runs-on: ubuntu-latest
    steps:
      - uses: jgillis/fetch-gh-release-asset
        with: 
          repo: "casadi/casadi"
          version: "tags/nightly-${{ github.event.inputs.branch }}"
          file: "*.whl"
          regex: true
      - run: ls
