on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        type: string
    
jobs:
  dev-release:
    if: "!contains(github.event.inputs.branch, 'release-')"
    runs-on: ubuntu-latest
    steps:
      - run: echo "foo"
