name: style

on: push

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0 # for git-restore-mtime

    - run: |
        mkdir build
        cd build
        cmake ..
        make lint
